// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"fr": &dictionary{index: frIndex, data: frData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Invalid PIN":                       1,
	"No video track":                    3,
	"PIN accepted, joining the call...": 2,
	"Please enter your PIN followed by # (use * to delete)\nEntered: %s": 0,
}

var enIndex = []uint32{ // 5 elements
	0x00000000, 0x00000045, 0x00000051, 0x00000073,
	0x00000082,
} // Size: 44 bytes

const enData string = "" + // Size: 130 bytes
	"\x02Please enter your PIN followed by # (use * to delete)\x0aEntered: %[" +
	"1]s\x02Invalid PIN\x02PIN accepted, joining the call...\x02No video trac" +
	"k"

var frIndex = []uint32{ // 5 elements
	0x00000000, 0x00000052, 0x00000064, 0x0000008d,
	0x000000a1,
} // Size: 44 bytes

const frData string = "" + // Size: 161 bytes
	"\x02Veuillez saisir votre code PIN suivi de # (utilisez * pour effacer)" +
	"\x0aSaisi : %[1]s\x02Code PIN invalide\x02Code PIN accepté, connexion en" +
	" cours...\x02Aucune piste vidéo"

	// Total table size 379 bytes (0KiB); checksum: CE247873
